In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Data Import

In [3]:
orders=pd.read_csv("Raw_data/orders DA.csv") 
products=pd.read_csv("Raw_data/products DA.csv")
order_items=pd.read_csv("Raw_data/order_items DA.csv")
customer=pd.read_csv("cleaned data/customer.csv")
inventory=pd.read_csv("cleaned data/inventory.csv")

In [11]:
inventory["warehouse_location"].value_counts()

warehouse_location
Chennai-WH5      190
Bengaluru-WH3    171
Hyderabad-WH4    167
Kolkata-WH6      166
Delhi-WH2        165
Mumbai-WH1       141
Name: count, dtype: int64

In [ ]:
# top 3 states by orders
orders["state"].value_counts().head(3).sort_values(ascending=False)

state
Uttar Pradesh    9507
Maharashtra      8179
Gujarat          3811
Name: count, dtype: int64

In [5]:
orders["status"].value_counts()

status
Delivered     32499
Cancelled      5996
Shipped        5071
Returned       3933
Processing     2501
Name: count, dtype: int64

In [9]:
order_items["category"].value_counts()

category
Office Supplies     10152
Home & Kitchen      10109
Electronics         10090
Grocery             10026
Fashion             10002
Toys & Baby          9989
Automotive           9986
Books                9949
Sports & Fitness     9903
Beauty & Health      9794
Name: count, dtype: int64

In [6]:
products.head()

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
0,PRD0001,Usha Smartphone Elite,Electronics,Smartphone,Usha,SKU-ELE-00001,92028,78958,55738,18,1144,250,SUP0198,4.3,3655,1,29-01-2025
1,PRD0002,Gizmore Smartphone Premium,Electronics,Smartphone,Gizmore,SKU-ELE-00002,91470,65917,48052,18,2857,2000,SUP0140,3.6,2321,1,17-05-2024
2,PRD0003,Fire-Boltt Smartphone Max,Electronics,Smartphone,Fire-Boltt,SKU-ELE-00003,148029,118800,68913,18,2349,250,SUP0113,3.5,4412,1,28-12-2024
3,PRD0004,Godrej Smartphone Elite,Electronics,Smartphone,Godrej,SKU-ELE-00004,152903,113203,80055,18,8130,250,SUP0068,4.5,1264,1,04-05-2023
4,PRD0005,HDFC Smartphone Elite,Electronics,Smartphone,HDFC,SKU-ELE-00005,18715,16226,8398,18,4729,1000,SUP0088,3.9,3700,1,27-11-2023

In [12]:
orders[(orders["order_date"]["total_amount"]==max(orders["total_amount"]))]

KeyError: 'total_amount'

Data Cleaning

In [8]:
customer.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                0
phone                0
city                 0
state                0
pincode              0
gender               0
age                  0
segment              0
registration_date    0
last_login_date      0
is_verified          0
is_active            0
total_orders         0
total_spent          0
dtype: int64

In [9]:
customer.duplicated().sum()

np.int64(0)

In [10]:
customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        10000 non-null  str
 1   first_name         10000 non-null  str
 2   last_name          10000 non-null  str
 3   email              10000 non-null  str
 4   phone              10000 non-null  int64
 5   city               10000 non-null  str
 6   state              10000 non-null  str
 7   pincode            10000 non-null  int64
 8   gender             10000 non-null  str
 9   age                10000 non-null  int64
 10  segment            10000 non-null  str
 11  registration_date  10000 non-null  str
 12  last_login_date    10000 non-null  str
 13  is_verified        10000 non-null  int64
 14  is_active          10000 non-null  int64
 15  total_orders       10000 non-null  int64
 16  total_spent        10000 non-null  float64
dtypes: float64(1), int64(6), str(10)
memory usage: 1.3 MB

In [11]:
customer.describe()

,phone,pincode,age,is_verified,is_active,total_orders,total_spent
count,1.000000e+04,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,1.000000e+04
mean,9.554707e+09,451127.435600,41.67630,0.841800,0.875500,5.000000,3.147386e+05
std,2.616962e+08,201801.014328,13.83438,0.364947,0.330168,3.069942,2.903266e+05
min,9.100093e+09,100006.000000,18.00000,0.000000,0.000000,0.000000,0.000000e+00
25%,9.327842e+09,277245.250000,30.00000,1.000000,1.000000,3.000000,8.842337e+04
50%,9.558696e+09,452011.000000,42.00000,1.000000,1.000000,5.000000,2.356611e+05
75%,9.781827e+09,627402.500000,54.00000,1.000000,1.000000,7.000000,4.660584e+05
max,9.999983e+09,799595.000000,65.00000,1.000000,1.000000,19.000000,1.999913e+06

In [12]:
customer.dtypes

customer_id              str
first_name               str
last_name                str
email                    str
phone                  int64
city                     str
state                    str
pincode                int64
gender                   str
age                    int64
segment                  str
registration_date        str
last_login_date          str
is_verified            int64
is_active              int64
total_orders           int64
total_spent          float64
dtype: object

In [13]:
customer["is_verified"]=customer["is_verified"].map({1:"verified",0:" not verified"})
customer["is_active"]=customer["is_active"].map({1:"active",0:"inactive"})

In [14]:
customer.head()

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
0,CUST00001,Kunal,Gupta,kunal.gupta223@gmail.com,9117912889,Guwahati,Assam,314040,Male,54,New,30-07-2024,10-04-2025,not verified,active,7,1028341.51
1,CUST00002,Aryan,Gupta,aryan.gupta336@yahoo.in,9271550550,Navi Mumbai,Maharashtra,799535,Female,26,Budget,05-07-2023,03-05-2024,verified,active,1,20337.39
2,CUST00003,Akash,Chatterjee,akash.chatterjee584@hotmail.com,9559676548,Surat,Gujarat,738196,Female,24,Regular,14-05-2022,31-10-2023,verified,active,7,265688.26
3,CUST00004,Madhuri,Walia,madhuri.walia878@gmail.com,9673322422,Gwalior,Madhya Pradesh,238106,Female,23,Regular,21-01-2025,22-05-2025,verified,inactive,7,173446.94
4,CUST00005,Vishal,Das,vishal.das342@yahoo.in,9920855521,Dhanbad,Jharkhand,783291,Female,59,Regular,06-06-2023,29-03-2024,verified,inactive,4,239808.60

In [15]:
inventory.isnull().sum()

inventory_id             0
product_id               0
warehouse_location       0
quantity_available       0
quantity_reserved        0
reorder_level            0
reorder_quantity         0
last_restocked_date      0
unit_cost                0
total_inventory_value    0
status                   0
dtype: int64

In [16]:
inventory.duplicated().sum()

np.int64(0)

In [17]:
inventory.describe()

,quantity_available,quantity_reserved,reorder_level,reorder_quantity,unit_cost,total_inventory_value
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,237.769000,9.632000,30.023000,105.592000,8280.788000,2.111910e+06
std,148.089494,6.057001,12.284029,55.977004,16131.315983,4.937672e+06
min,0.000000,0.000000,10.000000,20.000000,56.000000,0.000000e+00
25%,103.500000,4.000000,19.000000,60.000000,793.500000,1.182950e+05
50%,232.000000,9.000000,30.000000,94.000000,2160.500000,3.945015e+05
75%,373.000000,15.000000,41.000000,141.000000,7054.250000,1.610128e+06
max,500.000000,20.000000,50.000000,250.000000,102620.000000,4.353634e+07

In [18]:
inventory.dtypes

inventory_id               str
product_id                 str
warehouse_location         str
quantity_available       int64
quantity_reserved        int64
reorder_level            int64
reorder_quantity         int64
last_restocked_date        str
unit_cost                int64
total_inventory_value    int64
status                     str
dtype: object

In [19]:
#convert into date formate
inventory["last_restocked_date"] = pd.to_datetime(inventory["last_restocked_date"],format="%d-%m-%Y")

In [20]:
order_items.isnull().sum()

item_id            0
order_id           0
product_id         0
product_name       0
category           0
quantity           0
unit_price         0
gst_rate           0
gst_amount         0
discount_amount    0
total_price        0
dtype: int64

In [21]:
order_items.duplicated().sum()

np.int64(0)

In [22]:
order_items.describe()

,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,2.002070,13456.451340,12.302780,4245.110363,2704.271868,28608.926845
std,0.815986,26067.401044,8.363679,10262.578836,6853.933730,62345.070289
min,1.000000,108.000000,0.000000,0.000000,0.000000,87.430000
25%,1.000000,1263.000000,5.000000,150.975000,150.110000,2177.455000
50%,2.000000,3579.000000,12.000000,895.440000,523.110000,6910.665000
75%,3.000000,11526.000000,18.000000,3068.160000,1948.902500,22940.450000
max,3.000000,149361.000000,28.000000,80654.940000,88200.390000,528546.520000

In [23]:
order_items.columns

Index(['item_id', 'order_id', 'product_id', 'product_name', 'category',
       'quantity', 'unit_price', 'gst_rate', 'gst_amount', 'discount_amount',
       'total_price'],
      dtype='str')

In [24]:
order_items.dtypes

item_id                str
order_id               str
product_id             str
product_name           str
category               str
quantity             int64
unit_price           int64
gst_rate             int64
gst_amount         float64
discount_amount    float64
total_price        float64
dtype: object

In [25]:
orders.isnull().sum()

order_id                0
customer_id             0
order_date              0
order_time              0
status                  0
city                    0
state                   0
pincode                 0
total_amount            0
gst_amount              0
shipping_charge         0
discount_amount         0
final_amount            0
payment_method          0
shipping_partner        0
tracking_id             0
delivered_date      17501
is_cod                  0
channel                 0
dtype: int64

In [26]:
# Delivered orders with null delivered_date
orders[(orders['status'] == "Delivered") & (orders['delivered_date'].isnull())].count()

order_id            0
customer_id         0
order_date          0
order_time          0
status              0
city                0
state               0
pincode             0
total_amount        0
gst_amount          0
shipping_charge     0
discount_amount     0
final_amount        0
payment_method      0
shipping_partner    0
tracking_id         0
delivered_date      0
is_cod              0
channel             0
dtype: int64

In [27]:
orders[(orders['status'] == "Processecing") & (orders['delivered_date'].isnull())].sum()

order_id
customer_id
order_date
order_time
status
city
state
pincode               0
total_amount        0.0
gst_amount          0.0
shipping_charge       0
discount_amount     0.0
final_amount        0.0
payment_method
shipping_partner
tracking_id
delivered_date
is_cod                0
channel
dtype: object

In [28]:
orders[(orders['status'] == "Cancelled") & (orders['delivered_date'].isnull())].count()

order_id            5996
customer_id         5996
order_date          5996
order_time          5996
status              5996
city                5996
state               5996
pincode             5996
total_amount        5996
gst_amount          5996
shipping_charge     5996
discount_amount     5996
final_amount        5996
payment_method      5996
shipping_partner    5996
tracking_id         5996
delivered_date         0
is_cod              5996
channel             5996
dtype: int64

In [29]:
orders[(orders['status'] == "shipped") & (orders['delivered_date'].isnull())].count()

order_id            0
customer_id         0
order_date          0
order_time          0
status              0
city                0
state               0
pincode             0
total_amount        0
gst_amount          0
shipping_charge     0
discount_amount     0
final_amount        0
payment_method      0
shipping_partner    0
tracking_id         0
delivered_date      0
is_cod              0
channel             0
dtype: int64

In [30]:
orders[(orders['status'] == "returned") & (orders['delivered_date'].isnull())].count()

order_id            0
customer_id         0
order_date          0
order_time          0
status              0
city                0
state               0
pincode             0
total_amount        0
gst_amount          0
shipping_charge     0
discount_amount     0
final_amount        0
payment_method      0
shipping_partner    0
tracking_id         0
delivered_date      0
is_cod              0
channel             0
dtype: int64

In [31]:
orders["status"].value_counts()

status
Delivered     32499
Cancelled      5996
Shipped        5071
Returned       3933
Processing     2501
Name: count, dtype: int64

In [32]:
orders[orders['delivered_date'].isnull()]['status'].value_counts()

status
Cancelled     5996
Shipped       5071
Returned      3933
Processing    2501
Name: count, dtype: int64

In [33]:
orders['order_time'] = pd.to_datetime(orders['order_time'], format='%H:%M:%S', errors='coerce').dt.time

In [34]:
orders["order_date"] = pd.to_datetime(orders["order_date"])
orders["delivered_date"] = pd.to_datetime(orders["delivered_date"])
orders.dtypes

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13776\2982481176.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  orders["order_date"] = pd.to_datetime(orders["order_date"])
C:\Users\ASUS\AppData\Local\Temp\ipykernel_13776\2982481176.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  orders["delivered_date"] = pd.to_datetime(orders["delivered_date"])

order_id                       str
customer_id                    str
order_date          datetime64[us]
order_time                  object
status                         str
city                           str
state                          str
pincode                      int64
total_amount               float64
gst_amount                 float64
shipping_charge              int64
discount_amount            float64
final_amount               float64
payment_method                 str
shipping_partner               str
tracking_id                    str
delivered_date      datetime64[us]
is_cod                       int64
channel                        str
dtype: object

In [35]:
orders

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
0,ORD000001,CUST02946,2025-05-22,17:10:00,Processing,Pune,Maharashtra,300862,100984.19,16364.64,0,20486.45,100984.19,Cash on Delivery,BlueDart,TRK354572763,NaT,1,App
1,ORD000002,CUST04232,2023-10-16,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,2023-10-19,0,Website
2,ORD000003,CUST08078,2023-10-08,12:32:00,Cancelled,Meerut,Uttar Pradesh,294014,32557.06,3562.92,0,696.86,32557.06,Debit Card,Amazon Logistics,TRK338505401,NaT,0,App
3,ORD000004,CUST09612,2023-10-02,08:05:00,Delivered,Nashik,Maharashtra,626047,24836.94,3092.88,0,4029.94,24836.94,UPI,DTDC,TRK289792017,2023-10-09,0,Mobile Web
4,ORD000005,CUST03065,2024-06-15,20:19:00,Delivered,Moradabad,Uttar Pradesh,409210,156689.29,25092.36,0,7805.07,156689.29,UPI,Ecom Express,TRK978240041,2024-06-22,0,App
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD049996,CUST06694,2023-11-30,02:02:00,Returned,Varanasi,Uttar Pradesh,211491,2922.08,745.36,0,485.28,2922.08,Credit Card,Delhivery,TRK377660669,NaT,0,Mobile Web
49996,ORD049997,CUST01649,2025-03-29,01:04:00,Cancelled,Nagpur,Maharashtra,475562,1844.05,312.48,0,689.71,1844.05,UPI,DTDC,TRK973715414,NaT,0,App
49997,ORD049998,CUST03865,2024-12-14,00:35:00,Delivered,Pune,Maharashtra,132579,13023.59,1452.96,0,1647.00,13023.59,Debit Card,Ecom Express,TRK187824914,2024-12-18,0,App
49998,ORD049999,CUST04997,2025-01-02,22:57:00,Shipped,Varanasi,Uttar Pradesh,782507,25068.84,4137.84,0,2057.00,25068.84,Credit Card,BlueDart,TRK205502040,NaT,0,Website
49999,ORD050000,CUST03422,2024-05-10,00:14:00,Processing,Raipur,Chhattisgarh,406380,1861.38,235.32,0,334.94,1861.38,Cash on Delivery,Amazon Logistics,TRK253765683,NaT,1,Website

In [36]:
payment.isnull().sum()

payment_id            0
order_id              0
customer_id           0
payment_date          0
payment_time          0
payment_method        0
amount                0
status                0
transaction_id        0
bank_name             0
gateway               0
refund_amount         0
refund_date       50000
dtype: int64

In [37]:
payment.duplicated().sum()

np.int64(0)

In [38]:
payment.dtypes

payment_id            str
order_id              str
customer_id           str
payment_date          str
payment_time          str
payment_method        str
amount            float64
status                str
transaction_id        str
bank_name             str
gateway               str
refund_amount       int64
refund_date       float64
dtype: object

In [39]:
payment["payment_date"] = pd.to_datetime(payment["payment_date"],format="%d-%m-%Y")
payment["refund_date"] = pd.to_datetime(payment["refund_date"],format="%d-%m-%Y")

In [40]:
products.isnull().sum()

product_id       0
product_name     0
category         0
subcategory      0
brand            0
sku              0
mrp              0
selling_price    0
cost_price       0
gst_rate         0
hsn_code         0
weight_grams     0
supplier_id      0
rating           0
review_count     0
is_active        0
launch_date      0
dtype: int64

In [41]:
products.duplicated().sum()

np.int64(0)

In [42]:
products.columns

Index(['product_id', 'product_name', 'category', 'subcategory', 'brand', 'sku',
       'mrp', 'selling_price', 'cost_price', 'gst_rate', 'hsn_code',
       'weight_grams', 'supplier_id', 'rating', 'review_count', 'is_active',
       'launch_date'],
      dtype='str')

In [43]:
products.dtypes

product_id           str
product_name         str
category             str
subcategory          str
brand                str
sku                  str
mrp                int64
selling_price      int64
cost_price         int64
gst_rate           int64
hsn_code           int64
weight_grams       int64
supplier_id          str
rating           float64
review_count       int64
is_active          int64
launch_date          str
dtype: object

In [44]:
products["launch_date"] = pd.to_datetime(products["launch_date"],format="%d-%m-%Y")

In [45]:
returns.isnull().sum()

return_id           0
order_id            0
customer_id         0
return_date         0
reason              0
return_amount       0
refund_status       0
refund_date         0
return_condition    0
remarks             0
dtype: int64

In [46]:
returns.count()

return_id           10000
order_id            10000
customer_id         10000
return_date         10000
reason              10000
return_amount       10000
refund_status       10000
refund_date         10000
return_condition    10000
remarks             10000
dtype: int64

In [47]:
returns.duplicated().sum()

np.int64(0)

In [48]:
returns["reason"].value_counts()

reason
Size Issue                 1196
Changed Mind               1150
Damaged in Transit         1143
Wrong Product Delivered    1135
Defective Product          1134
Not as Described           1125
Duplicate Order            1081
Quality Issue              1075
Delayed Delivery            484
Better Price Found          477
Name: count, dtype: int64

In [59]:
returns.dtypes

return_id                      str
order_id                       str
customer_id                    str
return_date         datetime64[us]
reason                         str
return_amount              float64
refund_status                  str
refund_date         datetime64[us]
return_condition               str
remarks                        str
dtype: object

In [50]:
returns["return_date"] = pd.to_datetime(returns["return_date"],format="%d-%m-%Y")
returns["refund_date"] = pd.to_datetime(returns["refund_date"],format="%d-%m-%Y")

In [51]:
supplier.isnull().sum()

supplier_id           0
supplier_name         0
contact_person        0
email                 0
phone                 0
city                  0
state                 0
pincode               0
category              0
gstin                 0
payment_terms_days    0
rating                0
created_date          0
is_active             0
dtype: int64

In [52]:
supplier.duplicated().sum()

np.int64(0)

In [58]:
supplier.dtypes

supplier_id                      str
supplier_name                    str
contact_person                   str
email                            str
phone                          int64
city                             str
state                            str
pincode                        int64
category                         str
gstin                            str
payment_terms_days             int64
rating                       float64
created_date          datetime64[us]
is_active                        str
dtype: object

In [54]:
supplier["is_active"] = supplier["is_active"].map({1:"active",0:"inactive"})

In [57]:
supplier["created_date"] = pd.to_datetime(supplier["created_date"],format="%d-%m-%Y")

In [61]:
# Convert date columns
orders['order_date']   = pd.to_datetime(orders['order_date'], errors='coerce')
payment['payment_time'] = pd.to_datetime(payment['payment_time'], errors='coerce')
returns['return_date']  = pd.to_datetime(returns['return_date'], errors='coerce')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13776\3669447234.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  payment['payment_time'] = pd.to_datetime(payment['payment_time'], errors='coerce')

In [63]:
#save all files in Cleaned data folder
customer.to_csv("Cleaned data/customer.csv",index=False)
inventory.to_csv("Cleaned data/inventory.csv",index=False)
orders.to_csv("Cleaned data/orders.csv",index=False)
products.to_csv("Cleaned data/products.csv",index=False)
order_items.to_csv("Cleaned data/order_items.csv",index=False)
payment.to_csv("Cleaned data/payment.csv",index=False)
returns.to_csv("Cleaned data/returns.csv",index=False)
supplier.to_csv("Cleaned data/supplier.csv",index=False)